User create
hironobu1004/portfolio2 pull request #3
Opened 2020-08-22 09:00 UTC by hironobu1004

2020-08-24 01:54 UTC, yuki-tachi0219 requested changes
プルリクエストありがとうございます。
こちらでも動作確認しましたが、エラーなく動いていて良い感じですね 😄 

ここから、実務に即したRailsの書き方に近づけていきましょう！
指摘事項が多くて恐縮ですが、やりやすいところから修正したいただければと思います。

ご不明点などは適宜ご質問いただければと思います。
各指摘事項に返信を付ける形で質問いただいても構いませんので、よろしくお願いいたします。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
このファイルは使っていないはずなので、削除しておいてください。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +    def make
create というアクション名に変更をお願いします。Railsでは、新たなレコードを作るときのアクションはcreateと名付けるのが一般的です。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +        redirect_to("/users/#{@user.id}")
このコード、実は
`redirect_to @user`
と置き換えることができます。この方がRailsチックな書き方ですね。
updateアクションのredirect_toも同じ書き方にできます。
destroyアクションのredirect_toは若干書き方が変わりますが、似たような書き方にできます。

以下の記事が非常に参考になります。
https://qiita.com/Kawanji01/items/96fff507ed2f75403ecb

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +    def signup
newという名前に変更をお願いします。Railsでは、新規登録ページを開くときのアクション名をnewにするのが一般的です。
URLは/signupのままで大丈夫です。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +    def make
ここも、createという名前に変更をお願いします。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +           render("users/:id/edit")
ここもエラーが起きてしまいます。「"users/:id/edit.html.erb"っていうファイルは無いよ」というエラーです。
render "new"のときと同じく、render"edit" としましょう。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +        @user = User.find(params["id"])
このアクション内の @userをすべて user に置き換えてもうまくいきます(なぜうまくいくのか、是非考えてみてください)。
また、この場合は
`User.find(params[:id]).destroy`
と一行で書くこともできるので試してみてください。一行で書くなら@userやuserを定義する必要もなくなりますね。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/models/user.rb
> -    validates :password, presence: true, length: { minimum: 6 }
これらの設定は消さなくてもいいと思うのですが、エラーなどのトラブルがあったから消したのでしょうか 🤔 
このあたりの設定が難しそうなら、一旦ここはこのままパスして次の課題で取り組んでいただこうかなと思うのですがいかがでしょうか。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/views/layouts/application.html.erb
> +      <li><a href="/users/index"><font color="white">User List</a></font></li>
32~35行目の4つの`<li><a href... `は、link_toに置き換えて実装してみましょう。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/helpers/users_helper.rb
> +end
このヘルパーは使っていないようなので、削除しておいてください 🌀

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/views/users/show.html.erb
> +      <%= link_to "削除","/users/#{@user.id}", method: :delete %>
リンク先はedit_users_path(...)という書き方にしたいですね。
以下のページの「ルーティングの名前でリンク先を指定する」章を参考にしてみてください。
https://techacademy.jp/magazine/7286

2020-08-24 01:54 UTC, yuki-tachi0219 commented on config/routes.rb
> +delete "/users/:id",to:"users#destroy"
`resources :users` を用いると、indexからdestoryあたりまでを全部省略できます。
以下の記事の「RESTfulなルーティング」の章を参考にしてみてください。
https://qiita.com/Kawanji01/items/96fff507ed2f75403ecb

2020-08-24 01:54 UTC, yuki-tachi0219 commented on db/migrate/20200816033558_create_users.rb
>      end
既存のmigrationファイルは変更しないほうがいいですね。
db/migrate/20200703055421_create_users.rb は何も変更せずに、
db/migrate/20200820064925_add_password_to_users.rb の中に「passwordカラムをusersモデルに追加する」という文を入れてみてください。

2020-08-24 01:54 UTC, yuki-tachi0219 commented on test/controllers/users_controller_test.rb
> +end
testファイルは全て消していいですよ。
RSpecという別のタイプのテストを学んでいただく予定なので、今のところは削除しておいてください

2020-08-24 01:54 UTC, yuki-tachi0219 commented on test/fixtures/users.yml
> +  password: MyString
このファイルも今のところ使わないので、削除してOKです

2020-08-24 01:54 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +        flash[:notice] = "ユーザー登録が完了しました"
このフラッシュメッセージが表示されないみたいですね。
以下の資料をもとに実装にチャレンジしてみてください。

テキスト：https://railstutorial.jp/chapters/sign_up?version=4.2#sec-the_flash
動画(昔のバージョンのRailsTutorialなので若干気をつけてください)：
https://youtu.be/jYk3VJQ70mk?t=2805

2020-09-03 23:42 UTC, hironobu1004 commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
対応いたしました。

2020-09-03 23:44 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +    def make
対応いたしました。

2020-09-03 23:44 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +        redirect_to("/users/#{@user.id}")
対応いたしました。

2020-09-03 23:45 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +    def signup
対応いたしました。

2020-09-03 23:46 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +    def make
対応いたしました。

2020-09-04 10:05 UTC, hironobu1004 commented on test/controllers/users_controller_test.rb
> +end
対応いたしました。

2020-09-04 10:06 UTC, hironobu1004 commented on test/fixtures/users.yml
> +  password: MyString
対応いたしました。

2020-09-07 00:52 UTC, yuki-tachi0219 commented on test/controllers/users_controller_test.rb
> +end
users_controller_test.rbだけでなく、
他の◯◯_contoller_tesr.rbや、fixtures, helpersなどのフォルダも消してOKです。
testフォルダを丸ごと削除する感じでお願いします。

2020-09-07 00:52 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +        redirect_to("/users/#{@user.id}")
updateアクション、destroyアクションのredirect_toも修正お願いいたします 🙏

2020-09-09 11:39 UTC, hironobu1004 commented on test/controllers/users_controller_test.rb
> +end
testフォルダ削除いたしました。

2020-09-13 11:19 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +        flash[:notice] = "ユーザー登録が完了しました"
メッセージが出るようにいたしました。

2020-09-13 11:26 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +        redirect_to("/users/#{@user.id}")
destroyメソッドも同じように＠userで動くようですがよろしいでしょうか。

2020-09-15 00:09 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +        redirect_to("/users/#{@user.id}")
たしかに、destroyメソッドも `redirect_to @user` で問題なく動いているようですね。
ただ、この書き方はあまり良くないので修正したいです。

destroyメソッドでは、ユーザーデータをデータベースから削除しています。
@user内にはユーザーデータは残ったままになるので
`redirect_to @user`
を実行してもエラーは起きません。ただし、@user内で指定しているユーザーデータはもうデータベースに無いので、
Railsが「@userのページに行こうと思ったけど、データが無い。とりあえずユーザー一覧ページに飛ばしておけばいいかな」と判断し、ユーザー一覧ページにリダイレクトされます。

ユーザー一覧ページにリダイレクトされることがわかってるなら、最初から
`redirect_to users_url`
でユーザー一覧ページに行くようにさせる方が親切ですね。
このままだと、他のエンジニアがこのコードを見たときに「@userをdestoryしてるはずなのに、redirect_to @user してるのはなぜだ?」と混乱してしまうので、コードを見やすくするためにも`redirect_to users_url` に変更しておきましょう。

```
        @user = User.find(params["id"])          # @userにユーザーデータを入れる
        @user.destroy 　                       # @userを削除。@userの中にデータはまだ残ってる
        flash[:destroy] = "ユーザ情報を削除しました"
        redirect_to @user                      # @userのデータはデータベースにはもう登録されてない！ とりあえず/users ページにリダイレクトさせておくか
```

2020-09-15 23:08 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +        @user = User.find(params["id"])
おっしゃる通りuserでもうまく行きました。userで書き直しました。user = User.find(params["id"]).destroyの部分ですが、＠を使うのはviewファイルでも使用できるようにするためという理解でよろしいでしょうか。
destroyというビューファイルはないのでとくに＠をつける必要はないという理解です。
わからないのはredirect_to userの部分ですが、起動させてみるとuser listにきっちり移動するようです。なぜuserでuser listに移動するのかよくわからないため調べてみます。

2020-09-15 23:10 UTC, hironobu1004 commented on app/models/user.rb
> -    validates :password, presence: true, length: { minimum: 6 }
おっしゃる通り一旦パスして進みます。転職の面談でセキュリティー部分を質問されたのですが、よくわかりませんでした。なので、後ほどまとめてセキュリティの知識についてもお教えいただければ幸いです。

2020-09-15 23:21 UTC, hironobu1004 commented on app/helpers/users_helper.rb
> +end
削除いたしました！

2020-09-15 23:22 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +           render("users/:id/edit")
render"edit"で記載し直しました。

2020-09-15 23:52 UTC, hironobu1004 commented on app/views/layouts/application.html.erb
> +      <li><a href="/users/index"><font color="white">User List</a></font></li>
link_toで書き直しました！

2020-09-17 11:47 UTC, hironobu1004 commented on config/routes.rb
> +delete "/users/:id",to:"users#destroy"
resources :usersで記載し直しました。

2020-09-17 11:48 UTC, hironobu1004 commented on app/views/users/show.html.erb
> +      <%= link_to "削除","/users/#{@user.id}", method: :delete %>
編集と削除を相対パスで書き直しました。

2020-09-17 11:49 UTC, hironobu1004 commented on app/controllers/users_controller.rb
> +        redirect_to("/users/#{@user.id}")
詳細にありがとうございます。redirect_to users_urlを使い書き直しました。

2020-09-20 00:17 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +        @user = User.find(params["id"])
そのとおりです！viewファイルで使わないものは、@を付けなくていいんです。
なるべく@は付けたくないので、viewファイルに値を渡さなくていい場合は積極的に@を外しましょう 👍

2020-09-20 00:22 UTC, yuki-tachi0219 approved these changes
LGTMです！

2020-10-08 12:22 UTC, merged